:profile-summary: https://github-profile-summary-cards.vercel.app/api/cards/
:readme-stats: https://github-readme-stats.vercel.app/api/pin/
:theme: transparent
:user: trueNAHO
:utc: 1
:width-half: 49%

:user-github-involves: https://github.com/search?q=involves%3A{user}
:user-github: https://github.com/{user}

:user-github-repositories: {user-github}?tab=repositories

= About Me

image:{profile-summary}/profile-details?username={user}&theme={theme}[link={user-github-involves}, width=100%]
image:{profile-summary}/most-commit-language?theme={theme}&username={user}[link={user-github-involves}, width={width-half}]
image:{profile-summary}/repos-per-language?theme={theme}&username={user}[link={user-github-involves}, width={width-half}]
image:{profile-summary}/stats?theme={theme}&username={user}[link={user-github-involves}, width={width-half}]
image:{profile-summary}/productive-time?theme={theme}&username={user}&utcOffset={utc}[link={user-github-involves}, width={width-half}]
image:https://github-profile-trophy.vercel.app/?no-bg=true&no-frame=true&username={user}&rank=SECRET,SSS,SS,S,AAA,AA,A&theme=algolia[link={user-github-involves}]

[cols="1,100"]
|===
| Rank | Languages

^| S | https://awk.dev[AWK],
       https://common-lisp.net[Common Lisp],
       https://nixos.org/manual/nix/stable[Nix],
       https://www.rust-lang.org[Rust]

^| A | https://www.gnu.org/software/bash[Bash],
       link:https://en.wikipedia.org/wiki/C_(programming_language)[C]/link:https://isocpp.org[C++],
       https://www.lua.org[Lua]

^| B | https://fishshell.com[Fish],
       https://www.python.org[Python],
       https://tug.org[TeX]

^| C | https://www.vim.org[Vimscript]
^| D | https://www.haskell.org[Haskell]
^| E | https://en.wikipedia.org/wiki/JavaScripp[Javascript]

^| F | https://www.java.com[Java],
       https://elkowar.github.io/eww/expression_language.html#simple-expression-language[Yuck]
|===

NOTE: {user-github-involves}[{user}'s complete GitHub
Activity]

[#repositories]
= Repositories

== Configurations

image:{readme-stats}?repo=dotfiles&theme={theme}&username={user}[link={user-github}/dotfiles, width={width-half}]
image:{readme-stats}?repo=grub2-theme-vimix-very-dark-blue&theme={theme}&username={user}[link={user-github}/grub2-theme-vimix-very-dark-blue, width={width-half}]
image:{readme-stats}?repo=os&theme={theme}&username={user}[link={user-github}/os, width={width-half}]

== Miscellaneous

image:{readme-stats}?repo=Sweep&theme={theme}&username={user}[link={user-github}/Sweep, width={width-half}]
image:{readme-stats}?repo=advent-of-code&theme={theme}&username={user}[link={user-github}/advent-of-code, width={width-half}]
image:{readme-stats}?repo=asciidoctor.nix&theme={theme}&username={user}[link={user-github}/asciidoctor.nix, width={width-half}]
image:{readme-stats}?repo=logo&theme={theme}&username={user}[link={user-github}/logo, width={width-half}]
image:{readme-stats}?repo=trueNAHO&theme={theme}&username={user}[link={user-github}/trueNAHO, width={width-half}]
image:{readme-stats}?repo=university&theme={theme}&username={user}[link={user-github}/university, width={width-half}]

== Archives

image:{readme-stats}?repo=tic-tac-toe.cc&theme={theme}&username={user}[link={user-github}/tic-tac-toe.cc, width={width-half}]
image:{readme-stats}?repo=tic-tac-toe.rs&theme={theme}&username={user}[link={user-github}/tic-tac-toe.rs, width={width-half}]
